### ISSUE TITLE
Did you consider converting to ARC? File > edit > convert to > objective c ARC.

### ISSUE THREAD

**Issue by johndpope** [mrRay/vvopensource#15]
I ran this against vvmidi and it helped clean up a bunch of code. 
ARC is solid, one needs to be more diligent around strong references though.

**Comment by johndpope** [comment]
Actually this has helped me over come a bug I was having with a weird linking error CoreImage not found for x86 on xcode 7.

**Comment by johndpope** [comment]
fyi - ![screen shot 2015-07-08 at 4 30 47 pm](https://cloud.githubusercontent.com/assets/289994/8564392/c80506f0-258e-11e5-8a95-f3d3b0ffa13e.png)

**Comment by Enigma644** [comment]
I second the ARC conversion! Pretty please :-) It'd be really nice to not have the 80 compiler warning message I'm getting from VVOSC too!

**Comment by johndpope** [comment]
VVMidi did get me some mileage - this MIKMIDI code is pretty solid and actively maintained.
https://github.com/mixedinkey-opensource/MIKMIDI
