### ISSUE TITLE
Images with DPI > 72

### ISSUE THREAD

**Issue by digitalfx** [mrRay/vvopensource#20]
I'm not sure if this is intentional behaviour, but when calling
`VVBufferPool.globalVVBufferPool().allocBufferForNSImage(myImage)`
if the image passed in is higher in DPI than 72, the returned buffer is lower resolution than the original. 

Try loading the following image into ISF Editor, and you will see what I mean.
![512](https://cloud.githubusercontent.com/assets/6060466/13860202/161bae0e-ec7f-11e5-8a4f-a7e109bfc444.png)

Many thanks for the great frameworks :)

**Comment by digitalfx** [comment]
Just an update, I'm currently working around this by calling `CGImageForProposedRect:context:hints:` on NSImage and then creating the buffer with `allocBufferForCGImageRef:` instead, which is returning the correct sized buffer.

**Comment by mrRay** [comment]
i don't remember if it's the intentional behavior, but it sure seems like a bug right now- thanks for reporting this, commit 9a4789b79dae029b6fbd4f4625b3d331548ed499 should address it!

**Comment by digitalfx** [comment]
Fab, that's done the trick :)
