### ISSUE TITLE
Xcode 8 and quicktime.h

### ISSUE THREAD

**Issue by digitalfx** [mrRay/vvopensource#23]
Hi Ray

I realise Xcode 8 is still in Beta right now, but I thought I'd take a few projects for a spin to see how they work. Unfortunately VVBufferPool-mac fails to compile HapSupport.h with the following error:
`vvopensource/VVBufferPool/HapSupport.h:59:9: 'QuickTime/QuickTime.h' file not found`

I guess the pending doom of QuickTime's removal is already known, but thought it might be useful to add an issue anyway.

**Comment by lov** [comment]
Yep, a workaround for now is setting the Root SDK to 10.11 instead of 10.12

**Comment by digitalfx** [comment]
Great thanks, I'll give this a try :smiley:

**Comment by mrRay** [comment]
howdy-

thanks for reporting this- i was able to reproduce this error, and have made some changes that should fix it.  please pull the latest repos when you get a chance and let me know if you still have any problems!

cheers
: : ray

**Comment by digitalfx** [comment]
Perfect, works for me 👍
